# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Application\:
        resource: '../src/Application'
        exclude:
            - '../src/Application/Kernel.php'

    UI\Api\:
        resource: '../src/UI/Api'
        exclude:
            - '../src/UI/Api/Response/'
        tags:
            - 'controller.service_arguments'

    UI\Console\:
        resource: '../src/UI/Console'
        tags:
            - 'controller.service_arguments'

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
            - '../src/Infrastructure/Codeception/'

    Component\Employee\Module\EmployeeModule: ~
    Component\Company\Module\CompanyModule: ~
    Component\Department\Module\DepartmentModule: ~

    # Alias Module
    Component\Employee\Module\EmployeeModuleInterface: '@Component\Employee\Module\EmployeeModule'
    Component\Company\Module\CompanyModuleInterface: '@Component\Company\Module\CompanyModule'
    Component\Department\Module\DepartmentModuleInterface: '@Component\Department\Module\DepartmentModule'

    # Alias Repository
    Component\Employee\Repository\EmployeeRepositoryInterface: '@Infrastructure\Repository\EmployeeRepository'
    Component\Company\Repository\CompanyRepositoryInterface: '@Infrastructure\Repository\CompanyRepository'
    Component\Department\Repository\DepartmentRepositoryInterface: '@Infrastructure\Repository\DepartmentRepository'